### ISSUE TITLE
Beyond binary labels/sensitive attributes

### ISSUE THREAD

**Issue by HanXudong** [yuji-roh/fairbatch#1]
Hi Yuji,

Thanks for the great work. It seems that the implementation of the `adjust_lambda` function assumes binary labels/sensitive attributes, which differs from the approximation for multiclass setting that has been introduced in the paper.

For example, https://github.com/yuji-roh/fairbatch/blob/69c44e70deccf36e113399efa99481d4552b37a8/FairBatchSampler.py#L176-L179.

I am wondering if there is a plan for supporting multiclass labels/sensitive attributes?

Thanks, 
Xudong

**Comment by yuji-roh** [comment]
Hi Xudong, 

Thanks for your interest in our work and the great question! 
As you commented, we have currently open-sourced the binary settings of FairBatch.
Although we did not decide when to publicize the multi-class version, you can extend the current binary version with the following information.

To extend FairBatch to multi-class labels/sensitive attributes, we only need some slight modifications in the implementation.
For example, in the [adjust_lambda()](https://github.com/yuji-roh/fairbatch/blob/69c44e70deccf36e113399efa99481d4552b37a8/FairBatchSampler.py#L148) function, we need to update self.lb (i.e., lambda parameters in the paper) by comparing multiple z groups in a sequential manner (e.g., max_{j1}∈{0,1,...,n_{z−2}} |L_{1,j1}(w) − L_{1,j1+1}(w)|). You can find the details on page 4 of the [FairBatch paper](https://openreview.net/pdf?id=YNnpaAKeCfx). 

It might be a reasonable choice to set the data type of self.lb as a Python dictionary to handle multiple disparities (in the [initialization](https://github.com/yuji-roh/fairbatch/blob/69c44e70deccf36e113399efa99481d4552b37a8/FairBatchSampler.py#L67) of FairBatch). 
Here is an example with a pseudo-code, 
```
self.lbs = {}
for tmp_y in self.y_item:
    for tmp_zcomb in self.z_comb: # tmp_zcomb contains two z attributes to compare
        self.lbs[(tmp_y, tmp_zcomb)] = <lambda initialization>
```

After adjusting the lambdas, we can select samples in the [__iter__() function](https://github.com/yuji-roh/fairbatch/blob/69c44e70deccf36e113399efa99481d4552b37a8/FairBatchSampler.py#L305) with the updated lambdas.

Hope the above information can help you.
Again, thanks for your interest in our work!

Thanks,
Yuji

**Comment by HanXudong** [comment]
Thanks for your reply! This really helps.

Much appreciated!
